# Generated by Django 4.2.11 on 2024-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cif',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='componente',
            name='cod_componente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cod_pedido',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
